name: Tests
on: [push, pull_request]

jobs:
  BuildAndTestHaxe41:
    runs-on: ubuntu-latest
    steps:
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    
    - name: Install Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.1.5

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install libs
      run: |
        haxelib install utest
        haxelib install hxnodejs
        haxelib dev jsasync ./

    - name: Build tests
      run: haxe build-test.hxml

    - name: Run tests
      run: |
        echo "*** ES5 Tests ***"
        node ./bin/test-es5.js
        echo "*** ES5 Tests No Markers ***"
        node ./bin/test-es5-no-marker.js
        echo "*** ES6 Tests ***"
        node ./bin/test-es6.js
        echo "*** ES6 Tests No Markers ***"
        node ./bin/test-es6-no-marker.js
  
  BuildAndTestHaxe42:
    runs-on: ubuntu-latest
    steps:
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
          
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install libs
      run: |
        haxelib install utest
        haxelib install hxnodejs
        haxelib dev jsasync ./

    - name: Build tests
      run: haxe build-test.hxml

    - name: Run tests
      run: |
        echo "*** ES5 Tests ***"
        node ./bin/test-es5.js
        echo "*** ES5 Tests No Markers ***"
        node ./bin/test-es5-no-marker.js
        echo "*** ES6 Tests ***"
        node ./bin/test-es6.js
        echo "*** ES6 Tests No Markers ***"
        node ./bin/test-es6-no-marker.js

  BuildAndTestHaxe43:
    runs-on: ubuntu-latest
    steps:
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.0
          
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install libs
      run: |
        haxelib install utest
        haxelib install hxnodejs
        haxelib dev jsasync ./

    - name: Build tests
      run: haxe build-test.hxml

    - name: Run tests
      run: |
        echo "*** ES5 Tests ***"
        node ./bin/test-es5.js
        echo "*** ES5 Tests No Markers ***"
        node ./bin/test-es5-no-marker.js
        echo "*** ES6 Tests ***"
        node ./bin/test-es6.js
        echo "*** ES6 Tests No Markers ***"
        node ./bin/test-es6-no-marker.js

